export const STATUS_TONES = {
  new: "blue",
  scheduled: "blue",
  en_route: "teal",
  onsite: "emerald",
  paused: "amber",
  return_scheduled: "amber",
  pending_installation: "amber",
  pending_repair: "amber",
  completed: "emerald",
  canceled: "rose",
  cancelled: "rose",
  declined: "slate",
  diagnostic_paid_declined_repair: "slate",
  closed: "slate",
  no_work_needed: "slate",
  paid_closed: "emerald",
  unsecured_lead: "rose",
  unassigned: "rose",
  assigned: "blue",
  confirmed: "teal",
  late: "amber",
  escalated: "rose",
  none_due: "slate",
  parts_due: "amber",
  parts_paid: "emerald",
  labor_due: "amber",
  labor_paid: "emerald",
  partial: "amber",
  failed: "rose",
  none_needed: "slate",
  quoted: "blue",
  awaiting_payment: "amber",
  ready_to_order: "blue",
  ordered: "teal",
  shipped: "blue",
  delivered: "emerald",
  installed: "emerald",
  clear: "emerald",
  awaiting_callback: "amber",
  unread_message: "blue",
  unresolved: "rose",
  parts_overdue: "rose",
  due_today: "amber",
  collected: "emerald",
  ready: "emerald",
};

export const DISPATCH_GROUPS = ["unassigned", "assigned", "en_route", "late", "escalated"];

export const JOB_QUICK_ACTIONS = [
  "Assign tech",
  "Mark en route",
  "Mark onsite",
  "Request parts payment",
  "Mark part ordered",
  "Schedule return",
  "Mark labor due",
];
